env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs25
  global:
    - SOME_TOKEN=some_value

install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24;
    fi
  - if [ "$EMACS" = 'emacs25' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs25;
    fi


###
### the actual build/test command
###
### Use "make test-batch" to test without byte-compiling.
### The default command avoids byte-compiling on Emacs 22.
###

script:
  $EMACS --version && rm -rf ~/.org-export && ./test.sh

###
### settings
###

notifications:
  email: noah.hoffman@gmail.com

