language: generic

os:
  - linux
  - osx

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs25

install:
  - tests/install.sh

script:
  emacs --version

notifications:
  email: noah.hoffman@gmail.com

